#!/bin/bash

log() {
    echo -e "\033[$2m$1\033[0m"
}

error() {
    log "✖ $1" 31
}

ok() {
    log "✔ $1" 32
}

fail() {
    error "$1"
    exit 1
}

run() {
    $@; (test $? -eq 0 && ok "$*") || fail "$*"
}

add_plugin() {
  plugin_repo="https://github.com/$1.git"
  plugin_name=$(basename $1)
  run "cd $(git rev-parse --show-toplevel)"
  run "git submodule add $plugin_repo .vim/bundle/$plugin_name"
}

install() {
  repo_root=$(git rev-parse --show-toplevel)
  run cd "$repo_root"
  run git submodule init && git submodule update
  run cd "$HOME"
  [ -f '.vimrc' -a ! -h '.vimrc' ] && run "mv .vimrc .vimrc_old}"
  [ -d '.vim' -a ! -h '.vim' ] && run "mv .vim .vim_old"
  run "ln -sfn $repo_root/.vimrc .vimrc"
  run "ln -sfn $repo_root/.vim .vim"
}

case $1 in
  add-plugin)
    if [[ -z "$2" ]]; then
      fail 'Plugin repo not specified'
    fi
    add_plugin $2
    ;;
  install)
    install
    ;;
  *)
    fail 'Unknown command'
    ;;
esac
