#!/bin/bash

log() {
    echo -e "\033[$2m$1\033[0m"
}

error() {
    log "✖ $1" 31
}

ok() {
    log "✔ $1" 32
}

fail() {
    error "$1"
    exit 1
}

run() {
    $@; (test $? -eq 0 && ok "$*") || fail "$*"
}

add_plugin() {
  plugin_repo="https://github.com/$1.git"
  plugin_name=$(basename $1)

  if [[ "$2" = '--opt' ]]; then
    plugin_path=".vim/pack/bundle/opt/$plugin_name"
  else
    plugin_path=".vim/pack/bundle/start/$plugin_name"
  fi

  run "cd $(git rev-parse --show-toplevel)"
  run "git submodule add --name $plugin_name $plugin_repo $plugin_path"
}

install() {
  test "$1" != '--verbose' && q=' -q'

  run cd $(dirname $0)

  repo_root=$(git rev-parse --show-toplevel)

  # Fetch VIM plugins
  run git submodule init$q
  run git submodule update$q

  run cd "$HOME"

  # Rename existing .vimrc and .vim if needed
  [ -f '.vimrc' -a ! -h '.vimrc' ] && run "mv .vimrc .vimrc_old}"
  [ -d '.vim' -a ! -h '.vim' ] && run "mv .vim .vim_old"

  # Create (or replace) symlinks
  run "ln -sfn $repo_root/.vimrc .vimrc"
  run "ln -sfn $repo_root/.vim .vim"
}

case $1 in
  add-plugin)
    if [[ -z "$2" ]]; then
      fail 'Plugin repo not specified'
    fi
    add_plugin $2 $3
    ;;
  install)
    install $2
    ;;
  *)
    fail 'Unknown command'
    ;;
esac
